version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - REACT_APP_API_URL=$REACT_APP_API_URL npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build